### PR TITLE
Add Lightline theme

### PR DESCRIPTION
**Pull request by Nandax00**
Now using the defined palettes.

Modes:
image
image
image
image

Tabline:
image

### CODE REVIEW

**Comment by Nandax00** [comment]
>     * All the zeros are for `cterm` colors, right?
Yes, I didn't try to emulate these colors in `cterm`, probably a disclaimer would make sense.
>     * Can lightline tell the difference between visual and block-visual?
No, Visual, V-Block, V-Line are all colored by `s:p.visual`
>     * Could normal mode use a simpler gray color? I'm used to a very simple status line, but if other colorschemes use colors for normal node, then I guess it's fine.
I was using the gruvbox theme for a long time before I switched to melange, and so I tried to emulate the color choices of its status line here. Btw, most of the included themes have non-gray normal mode colors: https://github.com/itchyny/lightline.vim/blob/master/colorscheme.md
> I'd maybe swap `visual` and `replace`, so `insert` and `replace` both use warm colors.
I, personally, use the visual mode most often to select an arbitrary section, and then change that via `c`, so for me the stronger yellow color makes a lot of sense here. On the other hand, I never ever used Replace mode :D How about meeting in the middle: let's change "replace" to magenta?

**Comment by savq** [comment]
Ok. Then the changes I'd suggest are:

- Use light gray for normal mode.
- Use magenta for replace mode.
- Use green or cyan for command mode.

**Comment by Nandax00** [comment]
It's not possible to config the Command mode with Lightline, it seems. I've applied your other suggestions.

**Comment by savq** [comment]
Perfect. Thanks @Nandax00 for the PR!

**Pull request merged**
